driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: aws
    verifier:
      systems:
        - name: remote
          attrs_outputs:
            s3_bucket_id: s3_txt_bucket
            s3_object_id: s3_txt_files
          backend: aws
          controls:
            - aws_resources

suites:
  - name: extensive_suite

